# Generated by Django 4.2 on 2025-01-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Lagartija'), ('T', 'Tierra'), ('A', 'Electrico '), ('F', 'Fuego'), ('P', 'Planta'), ('A', 'Agua')], max_length=30),
        ),
    ]
